"""empty message

Revision ID: e507c11e6c0c
Revises: d37fee4d7578
Create Date: 2024-04-26 11:00:34.205063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e507c11e6c0c'
down_revision = 'd37fee4d7578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
    
    #execute sql for instance to update a previous value on the column
    #op.execute("UPDATE table set column=''")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
